name: query_assistant_padi
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  get: ^4.7.2
  delightful_toast: ^1.1.0
  flutter_screenutil: ^5.9.3
  line_icons: ^2.0.3
  html: ^0.15.6
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  skeletonizer: ^2.1.0+1
  photo_view: ^0.15.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  get_storage: ^2.1.1
  salomon_bottom_bar: ^3.3.2
  lazy_load_indexed_stack: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
